# Generated by Django 5.2.8 on 2025-11-26 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_siteconfiguration"),
    ]

    operations = [
        migrations.CreateModel(
            name="InvoiceConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        default="Your Company Name",
                        help_text="Business name displayed on invoice",
                        max_length=255,
                    ),
                ),
                (
                    "company_address",
                    models.TextField(
                        default="Your Address", help_text="Full company address"
                    ),
                ),
                (
                    "company_phone",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Contact phone number",
                        max_length=50,
                    ),
                ),
                (
                    "company_email",
                    models.EmailField(
                        blank=True,
                        default="",
                        help_text="Contact email address",
                        max_length=254,
                    ),
                ),
                (
                    "company_tin",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Tax Identification Number",
                        max_length=50,
                        verbose_name="TIN",
                    ),
                ),
                (
                    "bank_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Bank name for payment settlement",
                        max_length=255,
                    ),
                ),
                (
                    "bank_account_number",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Bank account number",
                        max_length=50,
                    ),
                ),
                (
                    "bank_account_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Account holder name",
                        max_length=255,
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        help_text="Company logo (recommended: 200x80px)",
                        null=True,
                        upload_to="invoice_logos/",
                    ),
                ),
                (
                    "theme",
                    models.CharField(
                        choices=[
                            ("minimal", "Minimal"),
                            ("classic", "Classic"),
                            ("modern", "Modern"),
                        ],
                        default="minimal",
                        help_text="Invoice theme style",
                        max_length=20,
                    ),
                ),
                (
                    "font_family",
                    models.CharField(
                        choices=[
                            ("Outfit", "Outfit"),
                            ("Inter", "Inter"),
                            ("Roboto", "Roboto"),
                            ("Poppins", "Poppins"),
                            ("Lato", "Lato"),
                            ("Open Sans", "Open Sans"),
                            ("Playfair Display", "Playfair Display"),
                            ("Merriweather", "Merriweather"),
                        ],
                        default="Outfit",
                        help_text="Font used in invoice",
                        max_length=50,
                    ),
                ),
                (
                    "primary_color",
                    models.CharField(
                        default="#1a1a1a",
                        help_text="Primary color for headers and accents (hex)",
                        max_length=7,
                    ),
                ),
                (
                    "secondary_color",
                    models.CharField(
                        default="#666666",
                        help_text="Secondary color for labels and borders (hex)",
                        max_length=7,
                    ),
                ),
                (
                    "background_color",
                    models.CharField(
                        default="#ffffff",
                        help_text="Background color (hex)",
                        max_length=7,
                    ),
                ),
                (
                    "accent_color",
                    models.CharField(
                        default="#4a90d9",
                        help_text="Accent color for highlights (hex)",
                        max_length=7,
                    ),
                ),
            ],
            options={
                "verbose_name": "Invoice Configuration",
                "verbose_name_plural": "Invoice Configuration",
            },
        ),
    ]
